name: lab_7_417877_test

on:
  push:
    branches:
      - lab_7/new_branch_417877

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install libs for testing
        run: |
          pip  install pytest

      - name: prepare environemnt
        run: |
          cd ./env_417877 && python -m pip install -r requirements.txt

      # - name: Run test
      #   run: |
      #     cd ./env_417877 && pytest calculator_test.py

  test_dodawanie:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install libs for testing
        run: |
          pip  install pytest

      - name: prepare environemnt
        run: |
          cd ./env_417877 && python -m pip install -r requirements.txt

      - name: Run test
        run: |
          cd ./env_417877 && pytest calculator_test.py::test_dodawanie

  test_odejmowanie:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install libs for testing
        run: |
          pip  install pytest

      - name: prepare environemnt
        run: |
          cd ./env_417877 && python -m pip install -r requirements.txt

      - name: Run test
        run: |
          cd ./env_417877 && pytest calculator_test.py::test_odejmowanie

  test_mnozenie:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install libs for testing
        run: |
          pip  install pytest

      - name: prepare environemnt
        run: |
          cd ./env_417877 && python -m pip install -r requirements.txt

      - name: Run test
        run: |
          cd ./env_417877 && pytest calculator_test.py::test_mnozenie

  test_dzielenie:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install libs for testing
        run: |
          pip  install pytest

      - name: prepare environemnt
        run: |
          cd ./env_417877 && python -m pip install -r requirements.txt

      - name: Run test
        run: |
          cd ./env_417877 && pytest calculator_test.py::test_dzielenie

  test_new:
    runs-on: ubuntu-latest
    needs:
      [build, test_dodawanie, test_odejmowanie, test_mnozenie, test_dzielenie]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install libs for testing
        run: |
          pip  install pytest

      - name: prepare environemnt
        run: |
          cd ./env_417877 && python -m pip install -r requirements.txt

      - name: Run test
        run: |
          cd ./env_417877 && pytest new_tests.py
